server:
  port: 8081
spring:
  profiles:
    active: druid # 环境设置
  application:
    name: vblog
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-file-size: 10MB #设置单个文件最大长度
      max-request-size: 100MB #最大请求文件的大小
  redis:
    # 地址
    host: 110.42.224.240
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: XwiRTdSC4OLfqyRm
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志输出配置
  mapper-locations: classpath:com/jzj/vblog/web/mapper/xml/*.xml  #xml文件位置

#分页插件PageHelper配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

#阿里云oss
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: LTAI5tPJqdTCFLCYhoBvApLN
    keySecret: tKfhKeOT3axaQhYLbpmznLXtVHZL7o
    bucketName: vue-vblog