server:
  port: 8081
  address: 0.0.0.0
spring:
  application:
    name: vBlog
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-file-size: 10MB #设置单个文件最大长度
      max-request-size: 100MB #最大请求文件的大小
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: /
    port: 5672
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: mm946232976@163.com
    password: SGfertCnIjKNm3x9 #登陆密码（或授权码）
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              fallback: false
              class: javax.net.ssl.SSLSocketFactory
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.47.88:3306/vblog?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 4odqqueypOUNTLEewKrFjrg5giHw5LHD
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志输出配置
  mapper-locations: classpath:com/jzj/vblog/web/mapper/xml/*.xml  #xml文件位置

#分页插件PageHelper配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

#阿里云oss
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: xxx
    keySecret: xxx
    bucketName: vue-vblog

#行为验证码相关
aj:
  captcha:
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    cache-type: redis
    # local缓存的阈值,达到这个值，清除缓存
    cache-number: 1000
    # local定时清除过期缓存(单位秒),设置为0代表不执行
    timing-clear: 180
    type: default
    water-mark: V-Blog
    slip-offset: 5 # 校验滑动拼图允许误差偏移量(默认5像素)
    aes-status: true # aes加密坐标开启或者禁用(true|false)
    interference-options: 2 # 滑动干扰项(0/1/2)
    font-style: 1 #点选字体样式 默认Font.BOLD
    font-size: 25 #点选字体字体大小
    history-data-clear-enable: false
    req-frequency-limit-enable: true # 接口请求次数一分钟限制是否开启 true|false
    req-get-lock-limit: 5 # 验证失败5次，get接口锁定
    req-get-lock-seconds: 120 # 验证失败后，锁定时间间隔,s
    req-get-minute-limit: 30 # get接口一分钟内请求数限制
    req-check-minute-limit: 60 # check接口一分钟内请求数限制
    req-verify-minute-limit: 60 # verify接口一分钟内请求数限制

Swagger:
  production: false
  enable: true
